package Dryves.Model;
// Generated 26-mrt-2013 21:03:05 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Factuur generated by hbm2java
 */
public class Factuur  implements java.io.Serializable {


     private int factuurnr;
     private int aankoopnr;
     private Date datum;
     private BigDecimal totaalbedrag;
     private BigDecimal totaalbedragexbtw;

    public Factuur() {
    }

    public Factuur(int factuurnr, int aankoopnr, Date datum, BigDecimal totaalbedrag, BigDecimal totaalbedragexbtw) {
       this.factuurnr = factuurnr;
       this.aankoopnr = aankoopnr;
       this.datum = datum;
       this.totaalbedrag = totaalbedrag;
       this.totaalbedragexbtw = totaalbedragexbtw;
    }
   
    public int getFactuurnr() {
        return this.factuurnr;
    }
    
    public void setFactuurnr(int factuurnr) {
        this.factuurnr = factuurnr;
    }
    public int getAankoopnr() {
        return this.aankoopnr;
    }
    
    public void setAankoopnr(int aankoopnr) {
        this.aankoopnr = aankoopnr;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public BigDecimal getTotaalbedrag() {
        return this.totaalbedrag;
    }
    
    public void setTotaalbedrag(BigDecimal totaalbedrag) {
        this.totaalbedrag = totaalbedrag;
    }
    public BigDecimal getTotaalbedragexbtw() {
        return this.totaalbedragexbtw;
    }
    
    public void setTotaalbedragexbtw(BigDecimal totaalbedragexbtw) {
        this.totaalbedragexbtw = totaalbedragexbtw;
    }




}


