package dryves;
// Generated 26-mrt-2013 21:03:05 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Aankoop generated by hbm2java
 */
public class Aankoop  implements java.io.Serializable {


     private int aankoopnr;
     private long ritnr;
     private int lidnr;
     private int ontmoetingnr;
     private String betaalwijze;
     private Date datum;
     private int factuurnr;

    public Aankoop() {
    }

	
    public Aankoop(int aankoopnr, long ritnr, int lidnr, int ontmoetingnr, int factuurnr) {
        this.aankoopnr = aankoopnr;
        this.ritnr = ritnr;
        this.lidnr = lidnr;
        this.ontmoetingnr = ontmoetingnr;
        this.factuurnr = factuurnr;
    }
    public Aankoop(int aankoopnr, long ritnr, int lidnr, int ontmoetingnr, String betaalwijze, Date datum, int factuurnr) {
       this.aankoopnr = aankoopnr;
       this.ritnr = ritnr;
       this.lidnr = lidnr;
       this.ontmoetingnr = ontmoetingnr;
       this.betaalwijze = betaalwijze;
       this.datum = datum;
       this.factuurnr = factuurnr;
    }
   
    public int getAankoopnr() {
        return this.aankoopnr;
    }
    
    public void setAankoopnr(int aankoopnr) {
        this.aankoopnr = aankoopnr;
    }
    public long getRitnr() {
        return this.ritnr;
    }
    
    public void setRitnr(long ritnr) {
        this.ritnr = ritnr;
    }
    public int getLidnr() {
        return this.lidnr;
    }
    
    public void setLidnr(int lidnr) {
        this.lidnr = lidnr;
    }
    public int getOntmoetingnr() {
        return this.ontmoetingnr;
    }
    
    public void setOntmoetingnr(int ontmoetingnr) {
        this.ontmoetingnr = ontmoetingnr;
    }
    public String getBetaalwijze() {
        return this.betaalwijze;
    }
    
    public void setBetaalwijze(String betaalwijze) {
        this.betaalwijze = betaalwijze;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public int getFactuurnr() {
        return this.factuurnr;
    }
    
    public void setFactuurnr(int factuurnr) {
        this.factuurnr = factuurnr;
    }




}


